# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20170124_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 24, 21, 3, 8, 15000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 24, 21, 3, 8, 15000, tzinfo=utc)),
        ),
    ]
